#!/bin/bash

show_help() {
    echo "##############################################"
    echo "                                              "
    echo "  Usage: Starts an existing Docker container  "
    echo "                                              "
    echo "  docker_start  [container name]              "
    echo "                                              "
    echo "##############################################"
}

die() {
    printf '%s\n' "$1"
    show_help
    exit 1
}

CONTAINER_NAME=""

# parse arguments
while [[ $# -gt 0 ]]; do
  key="$1"

  case $key in
    -h|--help)
      die
      ;;
    *)
      CONTAINER_NAME="$1"
      shift
      shift
      ;;
  esac
done

if [ -z "$CONTAINER_NAME" ]; then   
  die 'ERROR: need to specify a containername to build a container'
fi

xhost +si:localuser:root

docker start \
    -i \
    $CONTAINER_NAME

